include:
  - .gitlab-ci-test.yml
  - .gitlab-ci-deploy.yml

image: registry.gitlab.com/linumlabs/molecule-sandbox/build/node-env:latest

# Cache modules in between jobs for current branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - apt-cache/

variables:
  PROTEA_FRONTEND_CONTAINER_IMAGE: registry.gitlab.com/linumlabs/proteav2/testing/protea-frontend:$CI_BUILD_REF_NAME
  PROTEA_FRONTEND_CONTAINER_RELEASE_IMAGE: registry.gitlab.com/linumlabs/proteav2/release/protea-frontend:$CI_BUILD_REF_NAME
  PROTEA_BACKEND_CONTAINER_IMAGE: registry.gitlab.com/linumlabs/proteav2/testing/protea-backend:$CI_BUILD_REF_NAME
  PROTEA_BACKEND_CONTAINER_RELEASE_IMAGE: registry.gitlab.com/linumlabs/proteav2/release/protea-backend:$CI_BUILD_REF_NAME
  API_HOST: api-$CI_BUILD_REF_NAME.protea.io:3001/api
  GIT_SUBMODULE_STRATEGY: recursive
  #DOCKER_DRIVER: overlay2
  #DOCKER_HOST: tcp://localhost:2375
  NODE_OPTIONS: --max-old-space-size=4096
  TOOL_NODE_FLAGS: --max-old-space-size=4096

stages:
  - build
  - test
  - merge
  - docker-build
  - push
  - deploy
