.push_deploy:
  when: manual
  allow_failure: false

build:dev_monorepo:
  stage: build
  only:
    changes:
      - ApiServer/*
      - WebApp/*
  except: 
    - ^(?!(feature|bugfix).*$).*$
  artifacts:
    paths:
      - ApiServer/dist
      - WebApp/build
  script:
    - .gitlab-ci-scripts/mono-build.sh
    
test:dev_monorepo:
  stage: test
  only:
    changes:
      - ApiServer/*
      - WebApp/*
  except:
    - ^(?!(feature|bugfix).*$).*$
  dependencies:
    - build:dev_monorepo
  script:
    - .gitlab-ci-scripts/mono-test.sh
    
build:nightly_monorepo:
  stage: build
  only:
    refs:
      - nightly
    changes:
      - ApiServer/*
      - WebApp/*
  artifacts:
    paths:
      - ApiServer/dist
      - WebApp/build
  script:
    - .gitlab-ci-scripts/mono-build.sh
    
test:nightly_monorepo:
  stage: test
  only:
    refs:
      - nightly
    changes:
      - ApiServer/*
      - WebApp/*
  dependencies:
    - build:nightly_monorepo
  script:
    - .gitlab-ci-scripts/mono-test.sh

build:staging_monorepo:
  stage: build
  only:
    refs:
      - staging
    changes:
      - ApiServer/*
      - WebApp/*
  artifacts:
    paths:
      - ApiServer/dist
      - WebApp/build
  script:
    - .gitlab-ci-scripts/mono-build.sh
    
test:staging_monorepo:
  stage: test
  only:
    refs:
      - staging
    changes:
      - ApiServer/*
      - WebApp/*
  dependencies:
    - build:staging_monorepo
  script:
    - .gitlab-ci-scripts/mono-test.sh
    
merge:to_master:
  stage: merge
  only:
    - nightly
  script:
    - .gitlab-ci-scripts/configure-git.sh
    - git checkout master
    - git merge origin/nightly
    - git push

merge:to_staging:
  stage: merge
  extends: .push_deploy
  only:
    - master
  script:
    - .gitlab-ci-scripts/configure-git.sh
    - git checkout staging
    - git merge origin/master
    - git push

merge:to_production:
  stage: merge
  extends: .push_deploy
  only:
    - staging
  script:
    - .gitlab-ci-scripts/configure-git.sh
    - git checkout production
    - git merge origin/staging
    - git push