# If build passses tests, push to release CR
docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "Starting Docker build stage..."
    - echo "Override global 'before_script'"
  script:
    - apk add bash
    - .gitlab-ci-scripts/docker-compose-setup.sh
    - docker-compose -v
    - docker-compose build
    - docker-compose up -d
    - docker-compose down
    - docker-compose push
  only:
    - nightly
    - staging
    - production

deploy:
  stage: deploy
  image: alpine
  environment:
    name: $CI_BUILD_REF_NAME
  variables:
    CLUSTER: AmazonEKS_LinumLabs
    NAMESPACE: protea
  before_script:
    - echo "Starting deploy stage..."
    - echo "Override global 'before_script'"
  script:
    - apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl config set-cluster $CLUSTER --server="$KUBE_URL" --certificate-authority="$KUBE_CA_PEM_FILE"
    - kubectl config set-credentials admin --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster="$CLUSTER" --user=admin --namespace="$NAMESPACE"
    - kubectl config use-context default
    - kubectl config get-contexts
    - sed 's/_APP_/'"$CI_ENVIRONMENT_SLUG"'/g; s/_TAG_/'"$CI_BUILD_REF_NAME"'/g; s/_DATE_/'\"$(date +'%s')\"'/g' ./k8s-config/protea-deployment.yml > kubernetes.yml;
    - kubectl apply -f kubernetes.yml
  only:
    - nightly
    - staging
    - production
