version: '3.5'
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles --logpath=/dev/null
  apiserver:
    image: $PROTEA_BACKEND_CONTAINER_RELEASE_IMAGE
    build:
      context: .
      dockerfile: ./ApiServer/Dockerfile
    depends_on:
      - mongo
    ports:
      - 3001:3001
    links:
      - mongo
  webapp:
    image: $PROTEA_FRONTEND_CONTAINER_RELEASE_IMAGE
    build:
      context: .
      dockerfile: ./WebApp/Dockerfile
      args: 
        - API_HOST
        - API_SCHEMA
        - MAINNET_DAI_ADDRESS
        - RINKEBY_DAI_ADDRESS
        - GOERLI_DAI_ADDRESS
        - KOVAN_DAI_ADDRESS
        - ROPSTEN_DAI_ADDRESS
        - MAINNET_COMMUNITY_FACTORY_ADDRESS
        - RINKEBY_COMMUNITY_FACTORY_ADDRESS
        - GOERLI_COMMUNITY_FACTORY_ADDRESS
        - KOVAN_COMMUNITY_FACTORY_ADDRESS
        - ROPSTEN_COMMUNITY_FACTORY_ADDRESS
        - NODE_OPTIONS=--max-old-space-size=4096
    depends_on:
      - apiserver
    ports:
      - 3000:80
    links:
      - apiserver
volumes:
    mongodb:
