/*
 *
 * Events constants
 *
 */

enum ActionTypes {
  EVENT_META_REQUEST = 'protea/events/EVENT_META_REQUEST',
  EVENT_META_SUCCESS = 'protea/events/EVENT_META_SUCCESS',
  EVENT_META_FAILURE = 'protea/events/EVENT_META_FAILURE',
  SAVE_EVENT = 'protea/events/SAVE_EVENT',
  CHECK_STATUS = 'protea/events/CHECK_STATUS',
  STATUS_UPDATED = 'protea/events/STATUS_UPDATED',

  GET_EVENT = 'protea/events/GET_EVENT',

  EVENT_CREATE_TX_REQUEST = 'protea/events/EVENT_CREATE_TX_REQUEST',
  EVENT_CREATE_TX_SUCCESS = 'protea/events/EVENT_CREATE_TX_SUCCESS',
  EVENT_CREATE_TX_FAILURE = 'protea/events/EVENT_CREATE_TX_FAILURE',

  UPDATE_EVENT_REQUEST = 'protea/events/UPDATE_EVENT_REQUEST',
  UPDATE_EVENT_SUCCESS = 'protea/events/UPDATE_EVENT_SUCCESS',
  UPDATE_EVENT_FAILURE = 'protea/events/UPDATE_EVENT_FAILURE',

  START_EVENT_TX_REQUEST = 'protea/events/START_EVENT_TX_REQUEST',
  START_EVENT_TX_SUCCESS = 'protea/events/START_EVENT_TX_SUCCESS',
  START_EVENT_TX_FAILURE = 'protea/events/START_EVENT_TX_FAILURE',

  END_EVENT_TX_REQUEST = 'protea/events/END_EVENT_TX_REQUEST',
  END_EVENT_TX_SUCCESS = 'protea/events/END_EVENT_TX_SUCCESS',
  END_EVENT_TX_FAILURE = 'protea/events/END_EVENT_TX_FAILURE',

  CANCEL_EVENT_TX_REQUEST = 'protea/events/CANCEL_EVENT_TX_REQUEST',
  CANCEL_EVENT_TX_SUCCESS = 'protea/events/CANCEL_EVENT_TX_SUCCESS',
  CANCEL_EVENT_TX_FAILURE = 'protea/events/CANCEL_EVENT_TX_FAILURE',

  CHANGE_LIMIT_TX_REQUEST = 'protea/events/CHANGE_LIMIT_TX_REQUEST',
  CHANGE_LIMIT_TX_SUCCESS = 'protea/events/CHANGE_LIMIT_TX_SUCCESS',
  CHANGE_LIMIT_TX_FAILURE = 'protea/events/CHANGE_LIMIT_TX_FAILURE',

  MANUAL_CONFIRM_ATTEND_TX_REQUEST = 'protea/events/MANUAL_CONFIRM_ATTEND_TX_REQUEST',
  MANUAL_CONFIRM_ATTEND_TX_SUCCESS = 'protea/events/MANUAL_CONFIRM_ATTEND_TX_SUCCESS',
  MANUAL_CONFIRM_ATTEND_TX_FAILURE = 'protea/events/MANUAL_CONFIRM_ATTEND_TX_FAILURE',

  RSVP_TX_REQUEST = 'protea/events/RSVP_TX_REQUEST',
  RSVP_TX_SUCCESS = 'protea/events/RSVP_TX_SUCCESS',
  RSVP_TX_FAILURE = 'protea/events/RSVP_TX_FAILURE',

  CANCEL_RSVP_TX_REQUEST = 'protea/events/CANCEL_RSVP_TX_REQUEST',
  CANCEL_RSVP_TX_SUCCESS = 'protea/events/CANCEL_RSVP_TX_SUCCESS',
  CANCEL_RSVP_TX_FAILURE = 'protea/events/CANCEL_RSVP_TX_FAILURE',

  CONFIRM_ATTENDANCE_TX_REQUEST = 'protea/events/CONFIRM_ATTENDANCE_TX_REQUEST',
  CONFIRM_ATTENDANCE_TX_SUCCESS = 'protea/events/CONFIRM_ATTENDANCE_TX_SUCCESS',
  CONFIRM_ATTENDANCE_TX_FAILURE = 'protea/events/CONFIRM_ATTENDANCE_TX_FAILURE',

  CLAIM_GIFT_TX_REQUEST = 'protea/events/CLAIM_GIFT_TX_REQUEST',
  CLAIM_GIFT_TX_SUCCESS = 'protea/events/CLAIM_GIFT_TX_SUCCESS',
  CLAIM_GIFT_TX_FAILURE = 'protea/events/CLAIM_GIFT_TX_FAILURE',

}

export default ActionTypes;
