# Frontend Deployment (Pod)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protea-frontend-_TAG_
  namespace: protea-_APP_
  labels:
    app: protea-frontend-_TAG_
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protea-frontend-_TAG_
  
  # Pod template
  template:
    metadata:
      labels:
        app: protea-frontend-_TAG_
        date: _DATE_
    spec:
      containers:
        - name: _TAG_
          image: registry.gitlab.com/linumlabs/proteav2/release/protea-frontend:_TAG_
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gitlab-registry-protea
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: protea-frontend-_TAG_
  namespace: protea-_APP_
  labels:
    app: protea-frontend-_TAG_
    date: _DATE_
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: protea-frontend-_TAG_
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protea-backend-_TAG_
  namespace: protea-_APP_
  labels:
    app: protea-backend-_TAG_
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protea-backend-_TAG_

  # Pod template
  template:
    metadata:
      labels:
        app: protea-backend-_TAG_
        date: _DATE_
    spec:
      containers:
        - name: _TAG_
          image: registry.gitlab.com/linumlabs/proteav2/release/protea-backend:_TAG_
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
              name: env-secrets
      imagePullSecrets:
        - name: gitlab-registry-protea
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: protea-backend-_TAG_
  namespace: protea-_APP_
  labels:
    app: protea-backend-_TAG_
    date: _DATE_
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: protea-backend-_TAG_
