# Frontend Deployment (Pod)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protea-frontend
  namespace: protea-_APP_
  labels:
    app: protea-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protea-frontend
  
  # Pod template
  template:
    metadata:
      labels:
        app: protea-frontend
        date: _DATE_
    spec:
      containers:
        - name: _TAG_
          image: registry.gitlab.com/linumlabs/proteav2/release/protea-frontend:_TAG_
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: APP_NAME
              value: "protea_webapp"
            - name: APP_SCHEMA
              value: "https" # Check this
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_PORT
              value: "3000"
            # - name: API_HOST # This is set in GitLab CI
            #   value: "api-$CI_BUILD_REF_NAME.protea.io:3001/api/"
            - name: MAINNET_DAI_ADDRESS
              value: "0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359"
            - name: RINKEBY_DAI_ADDRESS
              value: "0xc77aC3D1D2f56f8F2003Ae1AD9872cc978b004d4"
            - name: MAINNET_COMMUNITY_FACTORY_ADDRESS
              value: ""
            - name: RINKEBY_COMMUNITY_FACTORY_ADDRESS
              value: "0xC5e72E3198f312369Ce2b4295e480732153D882a"
      imagePullSecrets:
        - name: gitlab-registry-protea
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: protea-frontend
  namespace: protea-_APP_
  labels:
    app: protea-frontend
    date: _DATE_
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: protea-frontend
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protea-backend 
  namespace: protea-_APP_
  labels:
    app: protea-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protea-backend

  # Pod template
  template:
    metadata:
      labels:
        app: protea-backend
        date: _DATE_
    spec:
      containers:
        - name: _TAG_
          image: registry.gitlab.com/linumlabs/proteav2/release/protea-backend:_TAG_
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: APP_NAME
              value: "protea_API_server"
            - name: APP_SCHEMA
              value: "https"
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_PORT
              value: "3001"
            - name: APP_ROUTE_PREFIX
              value: "/api"
            - name: APP_BANNER
              value: "true"
            - name: LOG_LEVEL
              value: "debug"
            - name: LOG_OUTPUT
              value: "dev"
            - name: MONGO_USERNAME
              value: "mongo-user"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: protea-mongo-auth
                  key: mongo-password
            - name: MONGO_HOST
              value: "mongo-protea.protea-_APP_"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DATABASE
              value: "PROTEA_DB"
            - name: MONGO_AUTH_SOURCE
              value: "admin"
            - name: BCRYPT_SALT_ROUND
              value: "10"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: protea-backend-jwt-secret
                  key: jwt-token
            - name: JWT_EXPIRY
              value: "1"
            - name: JWT_PERMIT_SALT
              valueFrom:
                secretKeyRef:
                  name: protea-backend-jwt-permit-salt-secret
                  key: jwt-salt
            - name: ETHERS_PROVIDER
              value: "default"
            - name: ETHERS_NETWORK
              value: "rinkeby"
            - name: ETHERS_RPC_PROVIDER_URL
              value: "http://localhost:8545" # TODO: update
            - name: INFURA_API_KEY
              value: "5b87341803ab415295dc6dd54b4239e6"
            - name: RINKEBY_COMMUNITY_FACTORY
              value: "0xC5e72E3198f312369Ce2b4295e480732153D882a"
            - name: MAINNET_COMMUNITY_FACTORY
              value: ""
            - name: APPLICATION_WALLET_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: protea-backend-wallet-private-key
                  key: wallet-private-key
            - name: APPLICATION_WALLET_MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: protea-wallet-mnemonic
                  key: wallet-mnemonic
      imagePullSecrets:
        - name: gitlab-registry-protea
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: protea-backend
  namespace: protea-_APP_
  labels:
    app: protea-backend
    date: _DATE_
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: protea-backend
